<?php

namespace App\Services\MetaAgents;

use App\Models\Agent;
use App\Models\AgentVersion;
use App\Models\MetaAgentAction;
use App\Models\MetaAgentRun;
use App\Support\Audit;
use Illuminate\Support\Str;

/**
 * Agent Builder Agent (PRD §12.2 — Phase 4).
 *
 * Reads the architecture plan (or a direct user prompt) and creates
 * native platform Agent rows + AgentVersion baseline. Generated agents
 * default to risk_level=L1 so risky behavior still requires explicit
 * elevation in the studio.
 */
class AgentBuilderAgent extends BaseMetaAgent
{
    public function kind(): string { return 'agent_builder'; }
    public function description(): string { return 'Creates / updates / deploys agents from a prompt or spec.'; }

    public function plan(MetaAgentRun $run): array
    {
        $spec = $run->plan['agents'] ?? [['name' => $run->prompt, 'risk_level' => 'L1']];
        $steps = [];
        foreach ($spec as $i => $a) {
            $steps[] = [
                'action' => 'generate',
                'subject_type' => 'agent',
                'input' => $a,
                'reasoning' => "Materialize agent #{$i}: " . ($a['name'] ?? 'unnamed'),
            ];
        }
        $steps[] = ['action' => 'test', 'subject_type' => 'qa', 'input' => ['scope' => 'agents']];
        return $steps;
    }

    public function executeStep(MetaAgentRun $run, MetaAgentAction $action): array
    {
        if ($action->action !== 'generate' || $action->subject_type !== 'agent') {
            return ['skipped' => true];
        }
        $spec = $action->input ?? [];
        $name = (string) ($spec['name'] ?? 'Generated Agent');
        $slug = Str::slug($name) . '-' . Str::random(4);

        $agent = Agent::create([
            'tenant_id'  => $run->tenant_id,
            'project_id' => $run->project_id,
            'name'       => $name,
            'slug'       => $slug,
            'description'=> $spec['description'] ?? "Auto-generated by Agent Builder meta-agent",
            'status'     => 'draft',
            'risk_level' => $spec['risk_level'] ?? 'L1',
            'max_risk_level_without_approval' => $spec['max_risk'] ?? 'L1',
            'environment_config' => ['source' => 'meta_agent_run:' . $run->id],
            'memory_scope' => $spec['memory_scope'] ?? 'session',
        ]);

        $version = AgentVersion::create([
            'agent_id' => $agent->id,
            'version'  => 1,
            'role'     => $spec['role'] ?? 'specialist',
            'system_instructions' => $spec['system_instructions'] ?? "You are {$name}, a specialist agent.",
            'model_config' => $spec['model_config'] ?? ['provider' => 'openai', 'model' => 'gpt-4o-mini'],
            'allowed_tools' => $spec['allowed_tools'] ?? [],
            'allowed_mcp_servers' => $spec['allowed_mcp_servers'] ?? [],
            'memory_scope' => $spec['memory_scope'] ?? 'session',
            'metadata' => ['generated_by' => 'agent_builder', 'changelog' => 'Auto-generated initial version'],
        ]);
        $agent->update(['current_version_id' => $version->id]);

        // Track artifact on the run.
        $artifacts = $run->artifacts ?? [];
        $artifacts['agents'][] = $agent->id;
        $run->update(['artifacts' => $artifacts]);

        Audit::record('meta_agent', 'agent_created', 'agent', $agent->id, [
            'meta_run' => $run->id, 'spec' => $spec,
        ], tenantId: $run->tenant_id);

        return ['agent_id' => $agent->id, 'slug' => $slug];
    }
}
