<?php

namespace App\Services\MetaAgents;

use App\Models\Agent;
use App\Models\McpServer;
use App\Models\MetaAgentAction;
use App\Models\MetaAgentRun;
use App\Models\Workflow;
use App\Support\Audit;
use Illuminate\Support\Facades\Storage;

/**
 * Documentation Agent (PRD §12.2 — Phase 4).
 *
 * Produces READMEs, architecture diagrams (Mermaid) and changelogs for
 * each artifact generated by the run. Documents are persisted under
 * storage/app/docs/<asset-type>/<id>/ and surfaced through the
 * Documentation viewer in the Agent Studio (Phase 4 UI).
 */
class DocumentationAgent extends BaseMetaAgent
{
    public function kind(): string { return 'documentation'; }
    public function description(): string { return 'Generates living documentation, READMEs and architecture diagrams.'; }

    public function plan(MetaAgentRun $run): array
    {
        return [['action' => 'generate', 'subject_type' => 'documentation', 'input' => []]];
    }

    public function executeStep(MetaAgentRun $run, MetaAgentAction $action): array
    {
        $files = [];
        foreach (Agent::whereIn('id', $run->artifacts['agents'] ?? [])->get() as $agent) {
            $md = $this->agentReadme($agent);
            $path = "docs/agent/{$agent->id}/README.md";
            Storage::disk('local')->put($path, $md);
            $files[] = $path;
        }
        foreach (Workflow::whereIn('id', $run->artifacts['workflows'] ?? [])->get() as $wf) {
            $md = $this->workflowReadme($wf);
            $path = "docs/workflow/{$wf->id}/README.md";
            Storage::disk('local')->put($path, $md);
            $files[] = $path;
        }
        foreach (McpServer::whereIn('id', $run->artifacts['mcp_servers'] ?? [])->get() as $s) {
            $md = $this->mcpReadme($s);
            $path = "docs/mcp_server/{$s->id}/README.md";
            Storage::disk('local')->put($path, $md);
            $files[] = $path;
        }

        $diagram = $this->architectureDiagram($run);
        Storage::disk('local')->put("docs/meta_agent_run/{$run->id}/architecture.mmd", $diagram);
        $files[] = "docs/meta_agent_run/{$run->id}/architecture.mmd";

        Audit::record('meta_agent', 'docs_generated', 'meta_agent_run', $run->id, ['files' => $files], tenantId: $run->tenant_id);
        return ['files' => $files, 'mermaid' => $diagram];
    }

    protected function agentReadme(Agent $a): string
    {
        return <<<MD
# {$a->name}

**Slug:** `{$a->slug}` · **Risk:** {$a->risk_level} · **Memory scope:** {$a->memory_scope}

## Description
{$a->description}

## Capabilities
- Provider: configured via Model Control Plane
- Memory scope: {$a->memory_scope}

_Auto-generated by the Documentation meta-agent._
MD;
    }

    protected function workflowReadme(Workflow $w): string
    {
        return <<<MD
# Workflow — {$w->name}

**Slug:** `{$w->slug}` · **Trigger:** {$w->trigger_type}

_Auto-generated by the Documentation meta-agent._
MD;
    }

    protected function mcpReadme(McpServer $s): string
    {
        return <<<MD
# MCP Server — {$s->name}

**Slug:** `{$s->slug}` · **Transport:** {$s->transport} · **Runtime:** {$s->runtime}

_Auto-generated by the Documentation meta-agent._
MD;
    }

    protected function architectureDiagram(MetaAgentRun $run): string
    {
        $lines = ["flowchart LR", "  user[User Prompt] --> arch[Platform Architect]"];
        foreach ($run->artifacts['agents'] ?? [] as $aId) {
            $lines[] = "  arch --> a{$aId}[Agent #{$aId}]";
        }
        foreach ($run->artifacts['workflows'] ?? [] as $wId) {
            $lines[] = "  arch --> w{$wId}[Workflow #{$wId}]";
        }
        foreach ($run->artifacts['mcp_servers'] ?? [] as $mId) {
            $lines[] = "  arch --> m{$mId}[MCP Server #{$mId}]";
        }
        return implode("\n", $lines) . "\n";
    }
}
