<?php

namespace App\Services\MetaAgents;

use App\Models\MetaAgentAction;
use App\Models\MetaAgentRun;
use App\Models\Template;
use App\Services\TemplateService;
use App\Support\Audit;

/**
 * Template Manager Agent (PRD §12.2 — Phase 4).
 *
 * Wraps Phase 2 TemplateService: when a meta-agent run produces a
 * coherent agent + workflow set the Template Manager packages them as
 * an installable template, computes manifest dependencies, and pushes
 * the package into the platform's template library.
 */
class TemplateManagerAgent extends BaseMetaAgent
{
    public function __construct(protected TemplateService $templates) {}

    public function kind(): string { return 'template_manager'; }
    public function description(): string { return 'Packages assets into installable templates and resolves dependencies.'; }

    public function plan(MetaAgentRun $run): array
    {
        return [
            ['action' => 'generate', 'subject_type' => 'template', 'input' => ['from_run' => $run->id]],
        ];
    }

    public function executeStep(MetaAgentRun $run, MetaAgentAction $action): array
    {
        $artifacts = $run->artifacts ?? [];
        $agentIds  = $artifacts['agents'] ?? [];
        $wfIds     = $artifacts['workflows'] ?? [];

        if (! $agentIds && ! $wfIds) return ['skipped' => 'no_assets'];

        $template = Template::create([
            'tenant_id'  => $run->tenant_id,
            'name'       => 'Bundle from run #' . $run->id,
            'slug'       => 'meta-bundle-' . $run->id,
            'asset_type' => 'bundle',
            'description'=> 'Auto-generated by Template Manager meta-agent',
            'payload'    => [
                'agents'      => $agentIds,
                'workflows'   => $wfIds,
                'mcp_servers' => $artifacts['mcp_servers'] ?? [],
                'generated_by'=> 'template_manager',
            ],
            'visibility' => 'tenant',
        ]);

        Audit::record('meta_agent', 'template_packaged', 'template', $template->id, [
            'meta_run' => $run->id,
        ], tenantId: $run->tenant_id);

        $artifacts['templates'][] = $template->id;
        $run->update(['artifacts' => $artifacts]);

        return ['template_id' => $template->id];
    }
}
