<?php

namespace App\Services\MetaAgents;

use App\Models\MetaAgentAction;
use App\Models\MetaAgentRun;
use App\Models\Workflow;
use App\Models\WorkflowVersion;
use App\Support\Audit;
use Illuminate\Support\Str;

/**
 * Workflow Builder Agent (PRD §12.2 — Phase 4).
 *
 * Translates the Platform Architect's workflow design into a native
 * platform Workflow + WorkflowVersion graph (React Flow compatible).
 */
class WorkflowBuilderAgent extends BaseMetaAgent
{
    public function kind(): string { return 'workflow_builder'; }
    public function description(): string { return 'Generates executable workflow graphs from specs or prompts.'; }

    public function plan(MetaAgentRun $run): array
    {
        $wf = $run->plan['workflow'] ?? null;
        if (! $wf) return [['action' => 'generate', 'subject_type' => 'workflow', 'input' => ['name' => 'Default', 'steps' => []]]];
        return [['action' => 'generate', 'subject_type' => 'workflow', 'input' => $wf]];
    }

    public function executeStep(MetaAgentRun $run, MetaAgentAction $action): array
    {
        if ($action->action !== 'generate' || $action->subject_type !== 'workflow') return ['skipped' => true];
        $spec = $action->input ?? [];
        $name = (string) ($spec['name'] ?? 'Generated Workflow');
        $slug = Str::slug($name) . '-' . Str::random(4);

        $graph = $this->buildGraph($spec['steps'] ?? [], $run);

        $workflow = Workflow::create([
            'tenant_id'   => $run->tenant_id,
            'project_id'  => $run->project_id,
            'name'        => $name,
            'slug'        => $slug,
            'status'      => 'draft',
            'risk_level'  => $spec['risk_level'] ?? 'L1',
            'trigger_type'=> $spec['trigger_type'] ?? 'manual',
            'schedule_config' => $spec['schedule_config'] ?? ($spec['schedule'] ?? null),
        ]);

        $version = WorkflowVersion::create([
            'workflow_id' => $workflow->id,
            'version'     => 1,
            'graph_json'  => $graph,
            'metadata'    => ['changelog' => 'Auto-generated by Workflow Builder meta-agent'],
        ]);
        $workflow->update(['current_version_id' => $version->id]);

        $artifacts = $run->artifacts ?? [];
        $artifacts['workflows'][] = $workflow->id;
        $run->update(['artifacts' => $artifacts]);

        Audit::record('meta_agent', 'workflow_created', 'workflow', $workflow->id, [
            'meta_run' => $run->id, 'node_count' => count($graph['nodes']),
        ], tenantId: $run->tenant_id);

        return ['workflow_id' => $workflow->id, 'node_count' => count($graph['nodes'])];
    }

    protected function buildGraph(array $steps, MetaAgentRun $run): array
    {
        $nodes = [['id' => 'start', 'type' => 'trigger', 'data' => ['label' => 'Start']]];
        $edges = [];
        $prev  = 'start';

        $agentIds = $run->artifacts['agents'] ?? [];
        $aIdx = 0;

        foreach ($steps as $idx => $step) {
            $nodeId = "step_{$idx}";
            $node = [
                'id'   => $nodeId,
                'type' => $step['type'] ?? 'agent',
                'data' => [
                    'label'    => $step['name'] ?? "Step " . ($idx + 1),
                    'agent_id' => $step['agent_id'] ?? ($agentIds[$aIdx] ?? null),
                    'config'   => $step['config'] ?? [],
                ],
            ];
            $nodes[] = $node;
            $edges[] = ['id' => "e_{$prev}_{$nodeId}", 'source' => $prev, 'target' => $nodeId];
            $prev = $nodeId;
            if ($node['type'] === 'agent') $aIdx++;
        }
        $nodes[] = ['id' => 'end', 'type' => 'output', 'data' => ['label' => 'End']];
        $edges[] = ['id' => "e_{$prev}_end", 'source' => $prev, 'target' => 'end'];

        return ['nodes' => $nodes, 'edges' => $edges];
    }
}
