<?php

namespace App\Services;

use App\Models\CodegenJob;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Str;

/**
 * OpenHands Software Agent SDK client (Phase 2).
 *
 * Talks to a sandboxed code-generation service over HTTP. When OPENHANDS_URL is
 * not set, returns deterministic local scaffolding so demos work offline.
 * The sandbox container in docker-compose is fronted by this client.
 */
class OpenHandsClient
{
    public function generateMcpServer(CodegenJob $job): CodegenJob
    {
        $job->update(['status' => 'running', 'started_at' => now()]);
        $url = env('OPENHANDS_URL');

        try {
            if ($url) {
                $resp = Http::timeout(60)->post(rtrim($url, '/') . '/v1/codegen/mcp', [
                    'prompt' => $job->prompt,
                    'inputs' => $job->inputs ?? [],
                    'job_id' => $job->id,
                ]);
                $files = $resp->successful() ? ($resp->json('files') ?? []) : $this->stubMcpServer($job);
                $branch = $resp->json('branch') ?? "openhands/codegen-{$job->id}";
                $prUrl = $resp->json('pr_url');
            } else {
                $files = $this->stubMcpServer($job);
                $branch = "openhands/codegen-{$job->id}";
                $prUrl = null;
            }

            $job->update([
                'status' => 'completed',
                'outputs' => ['files' => $files],
                'repo_branch' => $branch,
                'pr_url' => $prUrl,
                'completed_at' => now(),
            ]);
        } catch (\Throwable $e) {
            $job->update([
                'status' => 'failed',
                'outputs' => ['error' => $e->getMessage()],
                'completed_at' => now(),
            ]);
        }

        return $job->fresh();
    }

    /**
     * Local Phase 2 stub: produce a minimal Python MCP server scaffold.
     */
    protected function stubMcpServer(CodegenJob $job): array
    {
        $slug = Str::slug($job->inputs['name'] ?? 'generated-mcp');
        $tools = $job->inputs['tools'] ?? [['name' => 'ping', 'description' => 'Health check']];
        $toolStubs = collect($tools)->map(fn ($t) => "    @server.tool(name='{$t['name']}')\n    def {$t['name']}(payload: dict) -> dict:\n        # TODO: implement {$t['description']}\n        return {'ok': True}")->join("\n\n");
        return [
            "{$slug}/server.py" => "from mcp_server import Server\n\nserver = Server('{$slug}')\n\n{$toolStubs}\n\nif __name__ == '__main__':\n    server.run()\n",
            "{$slug}/Dockerfile" => "FROM python:3.12-slim\nWORKDIR /app\nCOPY . .\nRUN pip install --no-cache-dir mcp\nCMD [\"python\", \"server.py\"]\n",
            "{$slug}/tests/test_tools.py" => "def test_smoke(): assert True\n",
            "{$slug}/README.md" => "# {$slug}\n\nGenerated by OpenHands SDK (Phase 2 stub)\n\nPrompt: {$job->prompt}\n",
        ];
    }
}
